version: "3.1"

services:
  db:
    container_name: mongoDB
    image: mongo:latest
    restart: always
    volumes:
      - ./dutyData:/data/db
    environment:
      - MONGO_INITDB_DATABASE= Duty
    ports:
      - 27018:27017